apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
