apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app: prometheus-operator-hello
    release: my-prometheus-operator
  name: app-metrics
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
